post_install() {
	# Copiar a estrutura para os diretórios de destino
	local dirs=("usr" "etc" "opt")

	for dir in "${dirs[@]}"; do
    echo "Processando /usr/share/${pkgname}/${dir}"
		if [ -d "/usr/share/${pkgname}/${dir}" ]; then
			# Copiar os arquivos e subdiretórios de /usr/share/${pkgname}/${dir} para o sistema
			echo "Copiando de /usr/share/${pkgname}/${dir} para /"
			cp -a "/usr/share/${pkgname}/${dir}" "/"
		fi
	done
}
